parameters:
#    abelogin.example.class: Abe\loginBundle\Example

services:
#    abelogin.example:
#        class: %abelogin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
