<?php

namespace Abe\EmailMTGBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * email_infoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class emailInfoRepository extends EntityRepository
{
}
