<?php

namespace Abe\loginBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * projectsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class projectsRepository extends EntityRepository
{
}
