<?php

namespace Abe\loginBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * user2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class user2Repository extends EntityRepository
{
}
