<?php

namespace Abe\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * user_logRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class user_logRepository extends EntityRepository
{
}
