abe_file_upload_homepage:
    path:     /hello/{name}
    defaults: { _controller: AbeFileUploadBundle:Default:index }

File_upload:
    resource: "@AbeFileUploadBundle/Controller/UploadController.php"
    type:     annotation 
    
File_document:
    resource: "@AbeFileUploadBundle/Controller/DocumentController.php"
    type:     annotation 
    
