parameters:
#    abe_file_upload.example.class: Abe\FileUploadBundle\Example

services:
#    abe_file_upload.example:
#        class: %abe_file_upload.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
